name: Aggiorna la blocklist

on:
  schedule:
    - cron: '0 3 * * 1'  # Ogni lunedì alle 3:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Installa le dipendenze
        run: pip install requests

     - name: Esegui lo script di conversione
        run: python convert_ublacklist.py

      - name: Commit e push dei cambiamenti
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pihole_blocklist.txt
          git commit -m "Aggiornamento automatico della blocklist" || echo "Nessuna modifica"
          git push
